### ISSUE TITLE
FeedBook Api endpoint throws 403 error

### ISSUE THREAD

**Issue by kshitiz018** [JideGuru/FlutterEbookApp#103]
FeedBook Api endpoints throws 403 error. can you help me how to resolve this.
![Screenshot 2023-06-16 at 12 42 33 PM (1)](https://github.com/JideGuru/FlutterEbookApp/assets/93922602/ffcd4550-50bc-43d8-976c-90e5e6662434)

**Comment by JideGuru** [comment]
It seems the API is restricted in your location. Try using a VPN to mask your location and try again.
