### ISSUE TITLE
Highlights or notes are invalid on iOS

### ISSUE THREAD

**Issue by westernbuptboy** [JideGuru/FlutterEbookApp#114]
Dear developer, first of all, thank you very much for open-sourcing this great work. At present, I have customized the application I need based on yours, but now I encounter a troublesome problem: Currently, there is no problem with the highlight pop-up on Android, But on iOS. Highlights or notes are invalid. Have you resolved this issue now? Can you share your solution if it is resolved? thanks

**Comment by westernbuptboy** [comment]
<img width="378" alt="image" src="https://github.com/JideGuru/FlutterEbookApp/assets/41902297/d795ac8c-fb78-4896-8fd9-c3b5514037f6">
like this

**Comment by westernbuptboy** [comment]
maby i find the solution  update the flutter_inappwebview plugin https://github.com/pichillilorenzo/flutter_inappwebview/pull/1575

**Comment by westernbuptboy** [comment]
bug fixed

**Comment by JideGuru** [comment]
That's great. Perhaps you can share how you fixed it so others with this issue can also learn from it.
Thanks

**Comment by westernbuptboy** [comment]
just update flutter_inappwebview plugin to the latest version. the bug will be fixed.the author of the plugin fixed it last month https://github.com/pichillilorenzo/flutter_inappwebview/pull/1575

**Comment by JideGuru** [comment]
thanks for sharing
