### ISSUE TITLE
Is there any chance to download pdf file from google drive?

### ISSUE THREAD

**Issue by balgithhub** [JideGuru/FlutterEbookApp#13]
Is there any chance to download pdf file from google drive?

https://drive.google.com/open?id=1a8Qz3C0-pL7Qj7hD4n16QcfjZ0gltGDf

**Comment by JideGuru** [comment]
@balgithhub You'll have to convert the link to a download link

**Comment by balgithhub** [comment]
How we can convert? I got Unsupported operation error? Can you try from your end and advise?

**Comment by Mastersam07** [comment]
@balgithhub you should append `&export=download` to the google drive link. In your case, it should be something like:

https://drive.google.com/u/0/uc?id=1a8Qz3C0-pL7Qj7hD4n16QcfjZ0gltGDf&export=download

**Comment by JideGuru** [comment]
@balgithhub please try what @Mastersam07 suggested and give a feedback

**Comment by Mastersam07** [comment]
> /u/0/uc

Glad it works for you.

That's the format for downloading files from google drive........ The earlier link you sent has the argument open?id=1a8Qz3C0-pL7Qj7hD4n16QcfjZ0gltGDf which means to open the file with that id.

Using /u/0/uc?id=***************************** is google's way of preparing the file for export hence it goes with the export argument

**Comment by Mastersam07** [comment]
> its working fine now if I changed my doc id like below
> 
> https://drive.google.com/u/0/uc?id=xxxxxxxxxx&export=download
> 
> thank you very much Mastersam07 and JideGuru :):):)
> 
> what is mean by /u/0/uc?id= ????

Glad it works for you @balgithhub .

That's the format for downloading files from google drive........ The earlier link you sent has the argument `open?id=1a8Qz3C0-pL7Qj7hD4n16QcfjZ0gltGDf` which means to open the file with that id.

Using `/u/0/uc?id=*****************************` is google's way of preparing the file for export hence it goes with the export argument

**Comment by balgithhub** [comment]
Hi MasterSam07/JideGuru,

Again its not working for big pdf files, please advise.

https://drive.google.com/u/0/uc?id=1tHQrvDFoNOsy5gdhhQonYkn5MsDzsUFW&export=download
https://drive.google.com/u/0/uc?id=1vrVOLEGofRMwzGq_sa7WQKzFHfGakPOZ&export=download

**Comment by balgithhub** [comment]
This time i did not get any error, i got just empty screen.

**Comment by Mastersam07** [comment]
The first file should work perfectly.

For the second file, you could try https://drive.google.com/u/0/uc?export=download&confirm=lFL9&id=1vrVOLEGofRMwzGq_sa7WQKzFHfGakPOZ

The second file seems really large. By default, Google Drive tries to scan for viruses in the file hence you may not be able to download it. Chances are very high that Google Drive can't scan this file for viruses.

If you are to do this manually, you will have to confirm the download. Your URL should be in the format https://drive.google.com/u/0/uc?export=download&confirm=lFL9&id=1vrVOLEGofRMwzGq_sa7WQKzFHfGakPOZ

@balgithhub @JideGuru

**Comment by balgithhub** [comment]
Still, I got same error for 1st file, like loading window missing and got empty screen. 2nd file also same error.

**Comment by Mastersam07** [comment]
> Still, I got same error for 1st file, like loading window missing and got empty screen. 2nd file also same error.

Please read the last message and try the given link

**Comment by balgithhub** [comment]
I got same error after used this also.

https://drive.google.com/u/0/uc?export=download&confirm=lFL9&id=1vrVOLEGofRMwzGq_sa7WQKzFHfGakPOZ
