### ISSUE TITLE
i recemtly downloaded this code and after a week or two i started getting this error, can anyone help me? 

### ISSUE THREAD

**Issue by Tevintaylor** [JideGuru/FlutterEbookApp#16]
![WeChat Image_20200601012146](https://user-images.githubusercontent.com/35780553/83358473-66093700-a3a6-11ea-81c5-05003fc0c723.jpg)

**Comment by JideGuru** [comment]
Hello.
The API i am using moved some of the Endpoints but i fixed that yesterday.
Please Pull and run again. That should fixed it for you.

**Comment by Tevintaylor** [comment]
ok, thank you very much I almost lost hair trying to solve this problem, i relized that the api were giving a bit of trouble.

**Comment by JideGuru** [comment]
That solves this issue then.

**Comment by Tevintaylor** [comment]
pulling it right now

**Comment by Tevintaylor** [comment]
sorry, it took so long I was running it on both ios and android. it is working now thanks.
