### ISSUE TITLE
Can't open any of the books

### ISSUE THREAD

**Issue by kevindalvi** [JideGuru/FlutterEbookApp#29]
Hey I'm running the code in Intelli J with Flutter Plugin. Everything works great, except I can't open any of the books. Here's the issue that I get. What do you think could be the issue?

![image](https://user-images.githubusercontent.com/47362113/89619500-09ba0c00-d85c-11ea-9cd0-5f15936831f7.png)

**Comment by kevindalvi** [comment]
Hey @JideGuru hope all is well. Just checking in to see if you had an opportunity to look into this issue. Thanks so much!

**Comment by JideGuru** [comment]
@kevindalvi I've not really been chanced to look into the issue but I'll look into it tomorrow

**Comment by kevindalvi** [comment]
Thanks so much!

**Comment by JideGuru** [comment]
@kevindalvi Did you test on Android? If you tested, did It work?

**Comment by kevindalvi** [comment]
Hey unfortunately I don't have Android. I was testing it on iOS. And I keep getting the same error. 

![image](https://user-images.githubusercontent.com/47362113/90320385-f586a680-df0e-11ea-90a8-8c773066bdba.png)

**Comment by JideGuru** [comment]
The issue seems to be from the epub plugin. I am looking into the plugin to see if there's a fix

**Comment by Zhang-Jony** [comment]
@JideGuru Android is Ok, just appear in iOS.

**Comment by JideGuru** [comment]
@Zhang-Jony thanks. I am working on fixing the plugin

**Comment by kapiltandukar** [comment]
Same issue on iOS. working on android.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-11 at 09 05 57](https://user-images.githubusercontent.com/3233200/95669508-3ca4b700-0ba1-11eb-9ae4-0a25b4090542.png)

**Comment by kapiltandukar** [comment]
Hey @Zhang-Jony waiting for your response.

**Comment by Damianoux** [comment]
Same problem here running on ios14 emulator And ios13 real device. Any update?

**Comment by Xsidelight** [comment]
I have the same problem but on Android. Also in some books, it appears this kind of text, don't know if its a problem of plugin or epub itself.
![Screenshot_20210123-111926](https://user-images.githubusercontent.com/63785350/105571956-863e9980-5d6d-11eb-84d7-875d7c1dac31.jpg)
![Screenshot_20210123-112156](https://user-images.githubusercontent.com/63785350/105571958-89d22080-5d6d-11eb-99f6-cd0977c99e64.jpg)

**Comment by vassilisimon** [comment]
@JideGuru Could you please update the epub_viewer dependency?

**Comment by JideGuru** [comment]
@vassilisimon Yes, i will. I'm still working on migrating the plugin to a different native library

**Comment by kekelove92** [comment]
This bug is still appear. Any one have solution for that?

**Comment by de1mat** [comment]
> @vassilisimon Yes, i will. I'm still working on migrating the plugin to a different native library

Interested in which library you are migrating to?

**Comment by akshayindia** [comment]
Still facing the isuee. Please look into it.

**Comment by JideGuru** [comment]
This issue should be fixed now since I've migrated to a different library(https://github.com/Mantano/iridium)
