### ISSUE TITLE
The book does not start from the last page read. It always starts over.

### ISSUE THREAD

**Issue by erkerkan** [JideGuru/FlutterEbookApp#35]
I think there is a problem with the saveReadLocator or getLastReadLocator method.

**Comment by ofarukcinar** [comment]
@JideGuru  I have this problem. I used Android.

**Comment by MrUnfunny** [comment]
@JideGuru Is epub_kitty supposed to automatically handle the readLocator? Because I can't find a manual way to handle it through 
the plugin

**Comment by JideGuru** [comment]
@MrUnfunny epub_kitty is supposed to handle it automatically but the plugin seems faulty and the author is not active/merging PRs.

**Comment by JideGuru** [comment]
@erkerkan , @MrUnfunny , and @ofarukcinar  I have been able to fix this problem by working on a new epub plugin (https://github.com/JideGuru/epub_viewer) which supports the last locator. You can pull the latest commit to test
