### ISSUE TITLE
three dots are shown even there are no more texts to be shown.

### ISSUE THREAD

**Issue by mrifni** [JideGuru/FlutterEbookApp#39]
I think there is a problem with the description_text.dart component where for description with less than 300 texts it still shows ... at the end without the show more.

**Comment by parthpanchal123** [comment]
@JideGuru  @mrifni   I just submitted a pull request #40 that fixes this issue.

**Comment by JideGuru** [comment]
@mrifni #40 fixes this just as @parthpanchal123 stated
