### ISSUE TITLE
Book section Container overflow error

### ISSUE THREAD

**Issue by parthpanchal123** [JideGuru/FlutterEbookApp#42]
An overflow error caused due to harcoding size of the book-section-container .

![image](https://user-images.githubusercontent.com/20091596/94769515-d9ac6680-03cf-11eb-8dbd-add2d6d56716.png)

Pull request addressing this issue : https://github.com/JideGuru/FlutterEbookApp/pull/41

**Comment by JideGuru** [comment]
Thank you for your PR! @parthpanchal123

**Comment by parthpanchal123** [comment]
> Thank you for your PR! @parthpanchal123 

Welcome 😎
