### ISSUE TITLE
error api category

### ISSUE THREAD

**Issue by ibra2010** [JideGuru/FlutterEbookApp#48]
error api category Such as
science faction
thrillers
young adult
fairy tales
How can this problem be solved?

**Comment by JideGuru** [comment]
Can you add some helpful details, please?

**Comment by ibra2010** [comment]
![Uploading IMG_20201030_143512.jpg…]()
![Screenshot_2020-10-30-14-34-24-673_dev jideguru flutterEbookApp](https://user-images.githubusercontent.com/73691128/97706609-a2100780-1abe-11eb-89fb-54dfce2f0a66.jpg)

![Uploading Screenshot_2020-10-30-14-35-20-670_dev.jideguru.flutterEbookApp.jpg…]()
![Uploading Screenshot_2020-10-30-14-35-35-264_dev.jideguru.flutterEbookApp.jpg…]()

**Comment by ibra2010** [comment]
![IMG_20201030_143445](https://user-images.githubusercontent.com/73691128/97706768-df749500-1abe-11eb-8805-fccba75c2194.jpg)
![IMG_20201030_143512](https://user-images.githubusercontent.com/73691128/97706792-e9969380-1abe-11eb-95a7-ecdde2f3d428.jpg)
![Screenshot_2020-10-30-14-35-16-408_dev jideguru flutterEbookApp](https://user-images.githubusercontent.com/73691128/97706840-fe732700-1abe-11eb-9372-d48bdf891ed4.jpg)

**Comment by ibra2010** [comment]
There is an error displaying some category items
