### ISSUE TITLE
eBook cannot be read in Release Mode

### ISSUE THREAD

**Issue by cmd-dev** [JideGuru/FlutterEbookApp#49]
After downloading any book, clicking on the read now button to read the epub causes the app to instantly crash, it works fine in debug mode but crashes in release mode.

**Comment by JideGuru** [comment]
What platform??

**Comment by cmd-dev** [comment]
Android.
[https://github.com/JideGuru/epub_viewer/issues/23#issuecomment-707854528](url)
I fixed it via the above url. 
Any way to enable the shrinking and still have the epub reader work though?

**Comment by syedecryptr** [comment]
> Android.
> [https://github.com/JideGuru/epub_viewer/issues/23#issuecomment-707854528](url)
> I fixed it via the above url.
> Any way to enable the shrinking and still have the epub reader work though?

the link you shared is empty.

**Comment by webbanie** [comment]
I found some information here :
https://stackoverflow.com/questions/64172791/flutter-insecure-http-is-not-allowed-by-platform

**Comment by felixferr** [comment]
I fix it by adding this code on android/app/build.gradle: 
```
buildTypes {
        release {
           
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            shrinkResources false
            signingConfig signingConfigs.release

        }
    }
```
