### ISSUE TITLE
Stuck on download

### ISSUE THREAD

**Issue by aremenel24** [JideGuru/FlutterEbookApp#51]
When I downloaded the zip file, extracted it and run it on vs code, the app just stayed stuck on downloading. What do I do?  
![image](https://user-images.githubusercontent.com/81427434/113374802-92b02580-93a0-11eb-8b0e-bb16a732657a.png)

**Comment by JideGuru** [comment]
Is there any error message in your console?

**Comment by sidetraxaudio** [comment]
Same issue here. Looks like its a http not allowed on platform and needs to be https. The site looks like it supports https so should be an easy fix

I/flutter (10873): /storage/emulated/0/Flutter Ebook App/Romeo_and_Juliet.epub
E/flutter (10873): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: Bad state: Insecure HTTP is not allowed by platform: http://www.feedbooks.com/book/2936.epub
E/flutter (10873): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2434:7)
E/flutter (10873): #1      _HttpClient.openUrl (dart:_http/http_impl.dart:2341:7)
E/flutter (10873): #2      DefaultHttpClientAdapter.fetch
package:dio/…/adapters/io_adapter.dart:35
E/flutter (10873): #3      DioMixin._dispatchRequest
package:dio/src/dio.dart:919

**Comment by ZakaryaNoori** [comment]
Same here
![image](https://user-images.githubusercontent.com/66834670/114073466-8d7b3b00-98b8-11eb-85b2-279ce8e09348.png)

**Comment by JideGuru** [comment]
Fixed with this [commit ](https://github.com/JideGuru/FlutterEbookApp/commit/58b9235074bd6cd987bd8910810a6248cc598fe7)
