### ISSUE TITLE
Can't able to download big (above 2 mb) google drive files using your ebook app

### ISSUE THREAD

**Issue by Bal82** [JideGuru/FlutterEbookApp#53]
Can't able to download big (above 2 mb) google drive pdf files, But its working fine below 1 Mb file 

Below 1 MB file : https://drive.google.com/u/0/uc?id=13c70PtmTQPNZlFRomLi1LTYYVw6Kdu7v&export=download
Above 1 MB file : https://drive.google.com/u/0/uc?id=1Gz56d7oIK_mmTH7sd-B1T0niktkL-Arw&export=download

**Comment by JideGuru** [comment]
I used the Dio package for downloads. Please open an issue there. 
Thanks
