### ISSUE TITLE
More than 1 MB file not downloaded properly

### ISSUE THREAD

**Issue by Bal82** [JideGuru/FlutterEbookApp#57]
Both files have same permission

https://drive.google.com/u/0/uc?id=1JYYy6XAeFlXgznp3dBh16LdCYzms9zNW&export=download  -- Downloaded and working fine

https://drive.google.com/u/0/uc?id=1Gz56d7oIK_mmTH7sd-B1T0niktkL-Arw&export=download -- Downloaded but i got blank screen and not updated properly inside database

**Comment by JideGuru** [comment]
@Bal82 I'm not using google drive in this repo. If you have any issues download files with google drive links. please open an issue in Dio's repo(the plugin I used for downloading files) or Check google drive API if you can find any leads. Thanks
