### ISSUE TITLE
Implementing text to speech to the reader

### ISSUE THREAD

**Issue by austinmarner** [JideGuru/FlutterEbookApp#6]
I am thinking about adding text to speech to the epub reader but I'm not sure where are the definitions of the reader

**Comment by JideGuru** [comment]
The reader plugin is an overlay on the FolioReader plugin.
They removed TTS because it was buggy.

You can refer to this links.

https://github.com/FolioReader/FolioReaderKit
https://github.com/FolioReader/FolioReader-Android
