### ISSUE TITLE
flutter web support

### ISSUE THREAD

**Issue by vaaniiaa** [JideGuru/FlutterEbookApp#61]
hi buddy
thanks for such a good library.
I have to release a flutter app which can read epub books on android and web.
I want to know if you have any plan for new update on this library for supporting flutter web application also or not?
I could not find any flutter epub reader library for supporting web applications.

**Comment by kritika14092001** [comment]
I'm on it

**Comment by Dev-Feyisayo** [comment]
Thank you. We are waiting.

**Comment by bornakpaul** [comment]
I can take this task @JideGuru . Can you please assign it to me ?

**Comment by JideGuru** [comment]
There's a web version hosted now: https://openleaf.codemagic.app
