### ISSUE TITLE
Read Book not working

### ISSUE THREAD

**Issue by azerturk** [JideGuru/FlutterEbookApp#67]
i tested with Android 9 real device. Forexample if we run with release mode then if you set targetSdkVersion is 25 it is working
but if you install and uninstall app or manually deleting the data then downloads section shows only 1 book.

In  targetSdkVersion 28 and 29 it is not working. I also upgraded the "cached_network_image to 2.5.1" because of the error.
But i tested many times reading book and the download page not working. Reading book shows blank page after reloading and download page shows only the latest book.

On terminal it print "Unknown chunk type '200' " and also 
"Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.WindowInsetsAnimation$Callback" on path:"

if we run with debug mode then extra error invalid image data but same things not working also in debug mode.

**Comment by Alionides** [comment]
Yes its not working

**Comment by JideGuru** [comment]
It's working now
