### ISSUE TITLE
Provider setState() or markNeedsBuild() called during build 

### ISSUE THREAD

**Issue by kebsont** [JideGuru/FlutterEbookApp#7]
I want to update a book state from a page, but I got this error.
<pre>
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
        flutter: The following assertion was thrown while dispatching notifications for Book:
        flutter: setState() or markNeedsBuild() called during build.
</pre>
```
class BookCard extends StatelessWidget {
  final String img, filename, url;
  Book book;
  BookCard(
      {Key key,
      @required this.img,
      @required this.url,
      this.filename,
      this.book})
      : super(key: key);

@override
  Widget build(BuildContext context) {
    final BookProvider = Provider.of<BookProvider>(context);
    BookProvider.setEntry(book);
    return Container(
    child:  BookProvider.downloaded
                    ? GestureDetector(
                        onTap: () => {
                                     //Read the book without trying to download it*
                                      }
                    : GestureDetector(
                        onTap: () => {
                                       //Download it*
                                      }
```

And in the Provider Class
```
class BookProvider extends ChangeNotifier {
  final database = DownloadsDB.instance;
  bool downloaded = false;
  Book book;

void setEntry(value) {
    book = value;
    notifyListeners();
  }
...
}
```

**Comment by kebsont** [comment]
Any help please ?

**Comment by JideGuru** [comment]
Hey, seems your isn't relating to my `code` but i will try my best to help.
You seem to be getting this error because you are updating the book while the widget is still building.
You should consider adding a timer to this:

```
final BookProvider = Provider.of<BookProvider>(context);
    BookProvider.setEntry(book);
```
making it something like this :

```
Timer(Duration(seconds: 1), (){
      final BookProvider = Provider.of<BookProvider>(context);
      BookProvider.setEntry(book);
    });
```

OR you can find another way to update the book state.

I hope it helps

**Comment by kebsont** [comment]
Hi @JideGuru 
Thanks for your answer.
Yeah, I tried the Timer but it doesn't work. 
Because, the downloaded variable is called when the widget is building 
`child: bookProvider.downloaded          ? GestureDetector()` 
And if bookProvider is null, the app crashes

` 
@override
  Widget build(BuildContext context) {
   BookProvider bookProvider  = null; 
    Timer(Duration(seconds: 1), () {
      bookProvider= Provider.of<BookProvider>(context);

      bookProvider.setEntry(book);
    });`

**Comment by JideGuru** [comment]
Why not try 
`BookProvider bookProvider = BookProvider();`

**Comment by kebsont** [comment]
This one too.
It doesn't crash the app, but shows my logs permanently so fast.  I can't do anything except killing the app

**Comment by kebsont** [comment]
Your app never crashed When you just write this ?
`BookProvider.setEntry(book);`

**Comment by JideGuru** [comment]
> Your app never crashed When you just write this ?
> `BookProvider.setEntry(book);`

I didn't do anything like this. you can check my code.
i personally don't think you need to use `Provider` for `BookCards`

**Comment by JideGuru** [comment]
I have this in my code and they were used in an `onTap`.
```
Provider.of<DetailsProvider>(context, listen: false).setEntry(entry);
 Provider.of<DetailsProvider>(context, listen: false).getFeed(entry.author.uri.t);
```

**Comment by kebsont** [comment]
But if you do this, how can you know if the book is already downloaded  before tapping the OnTap button ? 
I mean this: 
`child: bookProvider.downloaded ? GestureDetector()
`

**Comment by JideGuru** [comment]
i think you can make you `BookCard `a `StatefulWidget `instead and in the `initState` of the `BookCard` you can check if the book is downloaded and update a `boolean` value for your `GestureDetector`. That way is Feasible

**Comment by kebsont** [comment]
I tried that this morning but it didn’t work, I think it was because I didn’t put the Timer. 

So I’ll try the Stateful and Timer at the same time and will go back to you.

**Comment by JideGuru** [comment]
Okay. Good luck with that!

**Comment by kebsont** [comment]
Yeah thank you

**Comment by kebsont** [comment]
@JideGuru  
I tried the stateful Widget and it seems like it works, but I'm confused with something.
`
class BookCd extends State<BookCard> {
@override
  void initState() {
    BookProvider bookProvider = BookProvider();
    BookProvider.getDownload(widget.book.id).then((c) {
      if (c.isNotEmpty) {
        setState(() {
          downloaded = true;
        });
      } else {
        setState(() {
          downloaded = false;
        });
      }
    });
    super.initState();
  }`

You know, it's a Book Card, so normally it is only the book tapped which has to be called or to be used in this whole class ?  
But my prolem is when I print the book inside the BookCard class, I see all the books from the API.
That's why, when I tap to download a book, it download another one, or when I try to get I downloaded book, I get another one.
Do you understand what I'm saying ?

**Comment by kebsont** [comment]
But the Timer doesn't work, the stateful widget method yes.

**Comment by JideGuru** [comment]
> @JideGuru
> I tried the stateful Widget and it seems like it works, but I'm confused with something.
> ` class BookCd extends State<BookCard> { @override void initState() { BookProvider bookProvider = BookProvider(); BookProvider.getDownload(widget.book.id).then((c) { if (c.isNotEmpty) { setState(() { downloaded = true; }); } else { setState(() { downloaded = false; }); } }); super.initState(); }`
> 
> You know, it's a Book Card, so normally it is only the book tapped which has to be called or to be used in this whole class ?
> But my prolem is when I print the book inside the BookCard class, I see all the books from the API.
> That's why, when I tap to download a book, it downloads another one, or when I try to get a downloaded book, I get another one.
> Do you understand what I'm saying ?

I don't get you.
Since this Issue is not related to this repository, why dont we talk about it else where?

**Comment by kebsont** [comment]
Ok, but where can we talk, so I can close the issue with the stateful Widget method
