### ISSUE TITLE
Permission denied creating path (on simulator, Android)

### ISSUE THREAD

**Issue by sgehrman** [JideGuru/FlutterEbookApp#8]
E/flutter (21181): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/Flutter Ebook App' (OS Error: Permission denied, errno = 13)

**Comment by sgehrman** [comment]
found out that targetSdkVersion 29 is causing this behaviour.  It works if I set it to 28.

See this: https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html

**Comment by JideGuru** [comment]
Does it happen when you set `targetSdkVersion` or when you use `Android 10`

**Comment by sgehrman** [comment]
I'm on Android 10.  I didn't investigate it much, I'm researching this problem at the moment.  I just set the targetSdkVersion to 28 and it started working.

**Comment by JideGuru** [comment]
Okay, i'd also look into it as soon as i'm free

**Comment by sgehrman** [comment]
getExternalStorageDirectory()

This method was deprecated in API level 29.
To improve user privacy, direct access to shared/external storage devices is deprecated. When an app targets Build.VERSION_CODES.Q, the path returned from this method is no longer directly accessible to apps. Apps can continue to access content stored on shared/external storage by migrating to alternatives such as Context#getExternalFilesDir(String), MediaStore, or Intent#ACTION_OPEN_DOCUMENT.

Replace that call and it should be fine.

**Comment by hhongak** [comment]
mark
