### ISSUE TITLE
Can't run this app first time

### ISSUE THREAD

**Issue by ninja1002** [JideGuru/FlutterEbookApp#86]
Target of URI doesn't exist: 'package:flutter/material.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

**Comment by OmarYehiaDev** [comment]
Try to run `flutter analyze` in the project root or `flutter doctor`

**Comment by pkwenda** [comment]
same question , run flutter analyze :
```
zhuangwendadeMacBook-Pro:FlutterEbookApp-master nonacosa$ flutter analyze
Because flutter_ebook_app depends on iridium_reader_widget from path which doesn't exist (could not find package iridium_reader_widget at "../iridium/reader_widget"), version solving failed.
Running "flutter pub get" in FlutterEbookApp-master...                  
pub get failed (66; Because flutter_ebook_app depends on iridium_reader_widget from path which doesn't exist (could not find package iridium_reader_widget at "../iridium/reader_widget"), version solving
failed.)
zhuangwendadeMacBook-Pro:FlutterEbookApp-master nonacosa$ 
```

**Comment by pkwenda** [comment]
https://codemagic.io/app/5e230defc5faa60315b1df62/build/628c24a623ff14297e053991

**Comment by jasjastone** [comment]
> same question , run flutter analyze :
> 
> ```
> zhuangwendadeMacBook-Pro:FlutterEbookApp-master nonacosa$ flutter analyze
> Because flutter_ebook_app depends on iridium_reader_widget from path which doesn't exist (could not find package iridium_reader_widget at "../iridium/reader_widget"), version solving failed.
> Running "flutter pub get" in FlutterEbookApp-master...                  
> pub get failed (66; Because flutter_ebook_app depends on iridium_reader_widget from path which doesn't exist (could not find package iridium_reader_widget at "../iridium/reader_widget"), version solving
> failed.)
> zhuangwendadeMacBook-Pro:FlutterEbookApp-master nonacosa$ 
> ```

I solve the issue by going to the pubspec.yaml file on line 40 and change 
    path: ../iridium/reader_widget 
to 
    path: ../iridium/reader_widget

**Comment by jasjastone** [comment]
hope it helps

**Comment by JideGuru** [comment]
This is fixed now
