### ISSUE TITLE
I got error like Unsupported operation while dowloading small pdf file (below 1 mb).

### ISSUE THREAD

**Issue by balgithhub** [JideGuru/FlutterEbookApp#9]
I got error like Unsupported operation while dowloading small pdf file (below 1 mb).

![image](https://user-images.githubusercontent.com/65658125/82551991-eb0e7800-9b7e-11ea-9204-e941ce715bc3.png)

**Comment by JideGuru** [comment]
Can you provide the link to the file please?

**Comment by balgithhub** [comment]
I tried both http and https link.

https://www.projectmadurai.org/pm_etexts/pdf/pm0001.pdf

http://www.projectmadurai.org/pm_etexts/pdf/pm0001.pdf

**Comment by JideGuru** [comment]
Can you post the error form `console` also.
also maybe the block of code that's throwing the error?
Thanks

**Comment by balgithhub** [comment]
I/flutter ( 8509): /storage/emulated/0/நூல்கள்/திருக்குறள்.pdf

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following UnsupportedError was thrown building DownloadAlert(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#1606c]], state: _DownloadAlertState#5f8c9):
Unsupported operation: Infinity or NaN toInt

The relevant error-causing widget was: 
  DownloadAlert file:///C:/Users/Kabilan/AndroidStudioProjects/books/lib/views/details.dart:354:29
When the exception was thrown, this was the stack: 
#0      double.toInt (dart:core-patch/double.dart:193:36)
#1      double.floor (dart:core-patch/double.dart:163:34)
#2      Constants.formatBytes (package:books/util/consts.dart:75:35)
#3      _DownloadAlertState.build (package:books/components/download_alert.dart:106:41)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by balgithhub** [comment]
did you tried downlod small pdf file (below 1 mb) file?

**Comment by JideGuru** [comment]
@balgithhub The app was made for ePub files. So i didn't download any pdf files at all

**Comment by JideGuru** [comment]
Where are you getting the pdf files from?
did you modify the app? 
A little information will help.

**Comment by balgithhub** [comment]
no i downloded lot of pdf files using with your app, but those are above 10 MB

**Comment by balgithhub** [comment]
I am not modifying anything on app level, on API file i used pdf file name

**Comment by balgithhub** [comment]
just chenged the pdf viewer instead of epub kitty

**Comment by JideGuru** [comment]
Okay, now that's some useful information.

**Comment by JideGuru** [comment]
I'll look into the problem and give you a response.
Thanks!

**Comment by balgithhub** [comment]
I changed these two files only
download.dart
--------------

onTap: () async{
                  String path = dl['path'];
                Navigator.push(context,
                MaterialPageRoute(builder: (context) => PDFScreen(path)),
                  );
                //pageChannel.receiveBroadcastStream().listen((Object event) {
                  //print('page:$event');
                //}, onError: null);
              },


Deatails.dart
--------------

startDownload(BuildContext context, String url, String filename) async{
    Directory appDocDir = Platform.isAndroid
        ? await getExternalStorageDirectory()
        : await getApplicationSupportDirectory();
    if(Platform.isAndroid){
      Directory(appDocDir.path.split("Android")[0]+"${Constants.appName}").create();
    }

    String path = Platform.isIOS
        ? appDocDir.path+"/$filename.pdf"
        : appDocDir.path.split("Android")[0]+"${Constants.appName}/$filename.pdf";
    print(path);
    File file = File(path);
    if(!await file.exists()){
      await file.create();
    }else{
      await file.delete();
      await file.create();
    }

**Comment by JideGuru** [comment]
@balgithhub I tried using this https://file-examples.com/wp-content/uploads/2017/10/file-example_PDF_500_kB.pdf. It's below (1 mb) and it works fine but your pdf didnt work 
I'm still looking into the problem but if you have any other helpful information, it'll be appreciated

**Comment by balgithhub** [comment]
For me also its working fine https://file-examples.com/wp-content/uploads/2017/10/file-example_PDF_500_kB.pdf. 

Could you please try below 200KB file?

**Comment by JideGuru** [comment]
i tried below 200kb also.
https://file-examples.com/wp-content/uploads/2017/10/file-sample_150kB.pdf
and it worked

**Comment by balgithhub** [comment]
For me also its working fine https://file-examples.com/wp-content/uploads/2017/10/file-sample_150kB.pdf. So size is not a problem. Something wrong on website access.

http://www.projectmadurai.org/pm_etexts/pdf/pm0001.pdf

**Comment by JideGuru** [comment]
Maybe you should look into that and tell me if you find something.
Thanks

**Comment by balgithhub** [comment]
What is this error?

E/flutter ( 8509): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'catalog.projectmadurai.org' (OS Error: No address associated with hostname, errno = 7)
E/flutter ( 8509): #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:963:7)
E/flutter ( 8509): <asynchronous suspension>
E/flutter ( 8509): #1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
E/flutter ( 8509): #2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
E/flutter ( 8509): #3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
E/flutter ( 8509): #4      new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter ( 8509): #5      _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 8509): #6      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 8509): #7      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 8509): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 8509): #9      _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 8509): #10     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 8509): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 8509): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 8509): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 8509): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 8509): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 8509):

**Comment by JideGuru** [comment]
The address (catalog.projectmadurai.org) can't be reach maybe because of internet issues or your server is down

**Comment by balgithhub** [comment]
No website is fine. I used your API file, just rename the site name.

**Comment by JideGuru** [comment]
Can you post the link to the file here?

**Comment by balgithhub** [comment]
http://www.projectmadurai.org/pm_etexts/pdf/pm0001.pdf

**Comment by JideGuru** [comment]
The link you just posted says "projectmadurai.org" but the error says "catalog.projectmadurai.org"
seems you added catalog and that caused the error

**Comment by balgithhub** [comment]
That is just dummy link. I hope you not change anything while download the new small pdf file.

**Comment by balgithhub** [comment]
I am changing only pdf file name on your API file.

**Comment by JideGuru** [comment]
Changing file name on my API?
i dont understand. Do you have access to the API Backend? 
How are you changing the name?

**Comment by balgithhub** [comment]
I used mockable.io site and created new API file.

**Comment by JideGuru** [comment]
new API files? or new PDF files?

**Comment by balgithhub** [comment]
new API file and just i put my pdf link.

**Comment by JideGuru** [comment]
Okay, can you post the link again? and also the error?

**Comment by balgithhub** [comment]
http://www.projectmadurai.org/pm_etexts/pdf/pm0001.pdf

**Comment by balgithhub** [comment]
I used your API file and just change the pdf file name. Got this error.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following UnsupportedError was thrown building DownloadAlert(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#a05c9]], state: _DownloadAlertState#8afa2):
Unsupported operation: Infinity or NaN toInt

The relevant error-causing widget was: 
  DownloadAlert file:///C:/Users/Kabilan/AndroidStudioProjects/books/lib/views/details.dart:354:29
When the exception was thrown, this was the stack: 
#0      double.toInt (dart:core-patch/double.dart:193:36)
#1      double.floor (dart:core-patch/double.dart:163:34)
#2      Constants.formatBytes (package:books/util/consts.dart:75:35)
#3      _DownloadAlertState.build (package:books/components/download_alert.dart:106:41)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
...

**Comment by JideGuru** [comment]
I really do not understand how you changed the files in my API because, the files from the App comes from [Feedbooks API](http://www.feedbooks.com/api). 
so you must be using your own API and your own files

**Comment by JideGuru** [comment]
Did you get any info after checking your website access?

**Comment by balgithhub** [comment]
Its not my website, its public website. Its my own API only. It's working fine for other sites only this site not working.

**Comment by balgithhub** [comment]
Did you add your website address anywhere in coding (except API file)?

**Comment by JideGuru** [comment]
No. It's only in the API file

**Comment by balgithhub** [comment]
Ok thanks. I will update if i resolved this issue.
