### ISSUE TITLE
Add support for zlibray...

### ISSUE THREAD

**Issue by ra-jain** [JideGuru/FlutterEbookApp#91]

**Comment by ra-jain** [comment]
Even though it is dead but we can access it from the tor browser at http://bookszlibb74ugqojhzhg2a63w5i2atv5bqarulgczawnbmsb6s6qead.onion/

**Comment by JideGuru** [comment]
Hi there, I have no intentions of supporting Z-Library as it goes against copyright laws. I only intend to support the Public domain with this project. Thanks

**Comment by ra-jain** [comment]
my bad thank you
